### ISSUE TITLE
Somethingawful Old Avatar Preview website defunct

### ISSUE THREAD

**Issue by SA-Flipperwaldt** [astral-sa/salr-redux#2]
This appears to be permanent. Just a heads up. By default a SOAP button is added to each post that now doesn't do anything useful.

The presence of this button can be disabled in preferences, so no biggie.

A lazy interim solution would be to change the default for this setting until there is time for a assumedly minor cleanup.

**Comment by astral-sa** [comment]
Future releases of the Firefox version will have some better, more familiar defaults.

**Comment by astral-sa** [comment]
I've changed the default of this setting for the next Firefox version, and from what I understand Master_Odin has plans to replace the link with another avatar-history site.
