### ISSUE TITLE
In quick reply, formatting shortcut keys open the Firefox sidebar.

### ISSUE THREAD

**Issue by SA-Flipperwaldt** [astral-sa/salr-redux#3]
This seems to be the case for me for ctrl-b and ctrl-i at least. The expected formatting tags are not inserted in the text field, even though it definitely is/was in focus. The Firefox sidebar is a column that pops in from the left that displays bookmarks or history or synced tabs.

I don't remember if this feature was supposed to be implemented yet or what, but either way, there it is.

**Comment by Samizdata** [comment]
I am seeing the same problem.

**Comment by astral-sa** [comment]
Thanks for the report! Will look into it after I've finished re-implementing avatar hiding.

**Comment by astral-sa** [comment]
Fixed this locally; expect it in the next Firefox release of SALR Redux!

**Comment by Samizdata** [comment]
Yay!  You ROCK!
